controller_list:
  - name: fake_simple_group_controller
    type: $(arg fake_execution_type)
    joints:
      - base_to_rotate_joint
initial:  # Define initial robot poses per group
  - group: simple_group
    pose: one